apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop  ##cluster name
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 1
    spot: true